# Stage 1: Build Next.js app
FROM --platform=$TARGETPLATFORM node:23-alpine AS builder

WORKDIR /app

ENV NEXT_PUBLIC_WS_URL="__NEXT_PUBLIC_WS_URL__"
ENV NEXT_PUBLIC_API_URL="__NEXT_PUBLIC_API_URL__"
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="__NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY__"
ENV NEXT_PUBLIC_CLERK_SIGN_IN_URL="__NEXT_PUBLIC_CLERK_SIGN_IN_URL__"
ENV NEXT_PUBLIC_CLERK_SIGN_UP_URL="__NEXT_PUBLIC_CLERK_SIGN_UP_URL__"
ENV NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL="__NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL__"
ENV NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL="__NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL__"
ENV NEXT_PUBLIC_LIVEKIT_URL="__NEXT_PUBLIC_LIVEKIT_URL__"

# Install dependencies
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm npm install

# Build the React app
COPY . .
RUN --mount=type=cache,target=/root/.next/cache npm run build

# Remove devDependencies to reduce image size
RUN npm prune --production && rm -rf node_modules/@next/swc*

# Stage 2: Serve the app
FROM --platform=$TARGETPLATFORM node:23-alpine

WORKDIR /app

COPY --from=builder /app/entrypoint.sh /app/entrypoint.sh
COPY --from=builder /app/public /app/public
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/next.config.js /app/next.config.js
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/.next /app/.next

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["npm", "start"]