version: "3.9"

services:
  server:
    image: adhupraba/discord-server:latest
    env_file:
      - .env.server
    container_name: discord_server
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1:4601/gateway/health/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    network_mode: host
    restart: always

  client:
    image: adhupraba/discord-client:latest
    env_file:
      - .env.client
    container_name: discord_client
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1:4600/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    network_mode: host
    restart: always
