//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Channels = newChannelsTable("public", "channels", "")

type channelsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	Name      postgres.ColumnString
	Type      postgres.ColumnString
	ProfileID postgres.ColumnString
	ServerID  postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz
	UpdatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ChannelsTable struct {
	channelsTable

	EXCLUDED channelsTable
}

// AS creates new ChannelsTable with assigned alias
func (a ChannelsTable) AS(alias string) *ChannelsTable {
	return newChannelsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ChannelsTable with assigned schema name
func (a ChannelsTable) FromSchema(schemaName string) *ChannelsTable {
	return newChannelsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ChannelsTable with assigned table prefix
func (a ChannelsTable) WithPrefix(prefix string) *ChannelsTable {
	return newChannelsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ChannelsTable with assigned table suffix
func (a ChannelsTable) WithSuffix(suffix string) *ChannelsTable {
	return newChannelsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newChannelsTable(schemaName, tableName, alias string) *ChannelsTable {
	return &ChannelsTable{
		channelsTable: newChannelsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newChannelsTableImpl("", "excluded", ""),
	}
}

func newChannelsTableImpl(schemaName, tableName, alias string) channelsTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		NameColumn      = postgres.StringColumn("name")
		TypeColumn      = postgres.StringColumn("type")
		ProfileIDColumn = postgres.StringColumn("profile_id")
		ServerIDColumn  = postgres.StringColumn("server_id")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, NameColumn, TypeColumn, ProfileIDColumn, ServerIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{NameColumn, TypeColumn, ProfileIDColumn, ServerIDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return channelsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Name:      NameColumn,
		Type:      TypeColumn,
		ProfileID: ProfileIDColumn,
		ServerID:  ServerIDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
