//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Channels = Channels.FromSchema(schema)
	Conversations = Conversations.FromSchema(schema)
	DirectMessages = DirectMessages.FromSchema(schema)
	Members = Members.FromSchema(schema)
	Messages = Messages.FromSchema(schema)
	Profiles = Profiles.FromSchema(schema)
	Servers = Servers.FromSchema(schema)
}
